modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="esradial"
version="${version}"
displayName="EsRadial"
description='''Reusable ApricityUI radial menus. Includes a default theme and replaceable renderer.'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies.esradial]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.esradial]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.esradial]]
modId="apricityui"
mandatory=true
versionRange="[1.2.3.1]"
ordering="AFTER"
side="CLIENT"
